### ISSUE TITLE
[Bug Report] WALC window closes every time the page is reloaded

### ISSUE THREAD

**Issue by YoungFellow-le** [WAClient/WALC#185]
**Describe the bug**
When you reload the page using `Ctrl`+`R` / `Ctrl`+`Shift`+`R` / `location.reload()` in the console, the window closes.

**WALC Installation Type:** All

**To Reproduce**
Steps to reproduce the behaviour:
1. Reload the page
2. See error

**Expected behaviour**
I just reloads the page without closing the window

**Did you try closing and then opening it back?:** Yes

**Comment by Zzombiee2361** [comment]
I said this before, reloading the page is an unsupported feature, I can add restart app button though. I think what happens is `whatsapp-web.js` tries to restart the browser when whatsapp is disconnected (which happens if you reload the page).

Last time you said that you need to reload the page to hide your chat, now that there's app lock you should try it and give me feedback on how it can be improved.

**Comment by YoungFellow-le** [comment]
I haven't tried the app lock yet. But the reason I reported this bug is because I was looking into the open chat without saving number feature.

**Comment by Zzombiee2361** [comment]
What that has to do with reloading the page? That said, opening a chat by a number could totally be added. You should've open a feature request for that.

**Comment by YoungFellow-le** [comment]
Can you leave it to me?
I'll commit to my fork then make a pull request.

**Comment by Zzombiee2361** [comment]
Oh ok then. Developing it is a pain sometime, when you modify nodejs or preload code, you need to restart the entire app to see the effect. No way around that unfortunately.

**Comment by YoungFellow-le** [comment]
I did web development before, don't worry :+1: 
And I'm quite experienced with JS

**Comment by Samisafool** [comment]
If I click "Update Whatsapp" it crashes too
